#!/bin/sh

# Remove the mesh
foamCleanPolyMesh
foamCleanTutorial

# Remove time folders
foamListTimes -rm -time 0: -withZero
rm -rf 0

# Remove processor directories
rm -rf  processor*

# Remove logs
rm  gradPOSC.txt log

