#!/bin/sh

cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

cp -r 0_org 0

# create the mesh
blockMesh
topoSet
refineMesh -overwrite
# snappyHexMesh -overwrite
# decomposePar -force
# snappyHexMesh -parallel -overwrite
# mpirun --oversubscribe -np 16 snappyHexMesh -overwrite
# reconstructParMesh -constant
# exit

# setFields

# # I.C.
funkySetFields -time 0

# exit

# # # # # for parallel running:
runApplication decomposePar

# runParallel renumberMesh -overwrite
#renumberMesh -overwrite
# runApplication renumberMesh -overwrite

# # # # # runParallel $(getApplication)
# mpirun -np 6 interIsoFoam
# mpirun --oversubscribe -np 10 interFoam -parallel
mpirun --oversubscribe -np 12 interFoam -parallel
